TOPDIR=../..


TESTS=cutilstest cutilstestsh  


cutilstest_TYPE=exe

cutilstest_SRC_EXTENSION=c

cutilstest_LIBS=cutils vtest


cutilstestsh_TYPE=exe

cutilstestsh_SRC_EXTENSION=c

cutilstestsh_LIBS=cutilssh vtest





include $(TOPDIR)/rules.make
