TOPDIR=../..


TESTS=hutilstestsh hutilstest


hutilstest_TYPE=exe

hutilstest_SRC_EXTENSION=c

hutilstest_LIBS=hutils vtest


hutilstestsh_TYPE=exe

hutilstestsh_SRC_EXTENSION=c

hutilstestsh_LIBS=hutilssh vtest





include $(TOPDIR)/rules.make
