TOPDIR=../..


TESTS=hutilstest hutilstestsh  


hutilstest_TYPE=exe

hutilstest_SRC_EXTENSION=c

hutilstest_LIBS=hutils cutils nutils vtest


hutilstestsh_TYPE=exe

hutilstestsh_SRC_EXTENSION=c

hutilstestsh_LIBS=hutilssh cutils nutils vtest





include $(TOPDIR)/rules.make
