TOPDIR=../..


TARGETS:=extlibexample

# ----------------------------------------------------------------------

extlibexample_TYPE=shlib

extlibexample_SRC_EXTENSION=c

# ----------------------------------------------------------------------

include $(TOPDIR)/rules.make
