TOPDIR=../..


TARGETS:=extlibexample

# ----------------------------------------------------------------------

extlibexample_TYPE=shlib

extlibexample_SRC_EXTENSION=c

# only cygwin needs this
extlibexample_LIBS=rtlib cutils butils nutils

# ----------------------------------------------------------------------

include $(TOPDIR)/rules.make
