TOPDIR=..

POSTBUILD_SUBDIRS=test

TARGETS:=iothread iothreadsh

# --- 

iothread_TYPE=lib

iothread_SRC_EXTENSION=c

iothread_CFLAGS=-Ilibevent/install/include


# --- 

iothreadsh_TYPE=shlib

iothreadsh_SRC_EXTENSION=c

iothreadsh_CFLAGS=-Ilibevent/install/include


include $(TOPDIR)/rules.make
