TOPDIR=..

POSTBUILD_SUBDIRS=test

TARGETS:=corothread corothreadsh

# --- 

corothread_TYPE=lib

corothread_SRC_EXTENSION=c


# --- 

corothreadsh_TYPE=shlib

corothreadsh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
