TOPDIR=../..


TESTS=cutilstestsh cutilstest


cutilstest_TYPE=exe

cutilstest_SRC_EXTENSION=c

cutilstest_LIBS=butils vtest


cutilstestsh_TYPE=exe

cutilstestsh_SRC_EXTENSION=c

cutilstestsh_LIBS=butilssh vtest





include $(TOPDIR)/rules.make
