TOPDIR=../..


TESTS=butilstestsh butilstest



butilstest_TYPE=exe

butilstest_SRC_EXTENSION=c

butilstest_LIBS=butils cutils vtest pthread



butilstestsh_TYPE=exe

butilstestsh_SRC_EXTENSION=c

butilstestsh_LIBS=butilssh cutilssh vtest pthread





include $(TOPDIR)/rules.make
