TOPDIR=..

TARGETS:=nutils nutilssh



# - sexe target compiles all files in current directory with extension *.c

nutils_TYPE=lib

nutils_SRC_EXTENSION=c


nutilssh_TYPE=shlib

nutilssh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
