TOPDIR=..

POSTBUILD_SUBDIRS=test

TARGETS:=nutils nutilssh

# ---

nutils_TYPE=lib

nutils_SRC_EXTENSION=c

# ---

nutilssh_TYPE=shlib

nutilssh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
