TOPDIR=../..


TESTS=tutilstestsh tutilstest 


tutilstest_TYPE=exe

tutilstest_SRC_EXTENSION=c

tutilstest_LIBS=tutils butils vtest pthread


tutilstestsh_TYPE=exe

tutilstestsh_SRC_EXTENSION=c

tutilstestsh_LIBS=tutilssh butilssh vtest pthread


include $(TOPDIR)/rules.make
