TOPDIR=..

POSTBUILD_SUBDIRS=test

TARGETS:=cutils cutilssh


# - sexe target compiles all files in current directory with extension *.c

cutils_TYPE=lib

cutils_SRC_EXTENSION=c


cutilssh_TYPE=shlib

cutilssh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
