TOPDIR=..

PREBUILD_SUBDIRS=libevent
POSTBUILD_SUBDIRS=test

TARGETS:=evcorothread evcorothreadsh

# --- 

evcorothread_TYPE=lib

evcorothread_SRC_EXTENSION=c

evcorothread_CFLAGS=-Ilibevent/install/include


# --- 

evcorothreadsh_TYPE=shlib

evcorothreadsh_SRC_EXTENSION=c

evcorothreadsh_CFLAGS=-Ilibevent/install/include


include $(TOPDIR)/rules.make
