#!/bin/bash


#set -x
set -e

pid=$1

if [ "x$pid" = "x" ]; then
      cat <<EOF
Usage: $0 <pid> [ -m -F ]

Description

The script performs the following steps
 - check if <pid> is that of a running process
 - check if <pid> is running from the same user account as current account
 - check if <pid> is that of a java process (running hostpot JVM)
 - Find jstack from the same JVM as that of the running process.
 - run jstack

The first command line parameter is the process id of the java process to monitor,
after the first option come additional options passed as is to jstack (optional)

EOF
   exit 1 
fi


if [ ! -d /proc/$pid ]; then
  echo "Error: The process $pid is not running"
  exit 1
fi

user=`stat -c "%U" /proc/$pid`
if [ "x$user" != "x$USER" ]; then
  echo "Error: The process $pid runs under user $user, this script should run under the same account"
  exit 1
fi

jvm_so=`grep libjvm.so /proc/$pid/maps |  head -1 | awk '{ print \$6 }'`

jstack_dir=$jvm_so
while [ ! -f "${jstack_dir}/bin/jstack" ];
do 
  if [ "x${jstack_dir}" = "x" ]; then
     echo "The JDK in $jvm_so not contain jstack, can't run."
     exit 1
  fi
  jstack_dir=`dirname $jstack_dir`
done

shift 
$jstack_dir/bin/jstack -l $@ $pid 
