TOPDIR=../..



TARGETS:=cpplib cpplibso


# - sexe target compiles all files in current directory with extension *.c

cpplib_TYPE=lib

cpplib_SRC_EXTENSION=cpp

cpplibso_TYPE=shlib

cpplibso_SRC_EXTENSION=cpp

cpplibso_LIBS=stdc++

include $(TOPDIR)/rules.make