TOPDIR=../..


TESTS=nutilstestsh nutilstest


nutilstest_TYPE=exe

nutilstest_SRC_EXTENSION=c

nutilstest_LIBS=nutils vtest


nutilstestsh_TYPE=exe

nutilstestsh_SRC_EXTENSION=c

nutilstestsh_LIBS=nutilssh vtest





include $(TOPDIR)/rules.make
