TOPDIR=../../..


TESTS= mdbgtest3


TEST_TOOL=true

#--

mdbgtest3_TYPE=exe

mdbgtest3_SRC=test3.cpp

mdbgtest3_CFLAGS=-I..

mdbgtest3_LIBS=dbgmemutil stdc++

mdbgtest3_POSTBUILD=./mdbgtest3.pl ${ROOT_DIR}/scripts
 
#--


include $(TOPDIR)/rules.make
