TOPDIR=..

POSTBUILD_SUBDIRS=errorp test

TARGETS:=butils butilssh 

# --- 

butils_TYPE=lib

butils_SRC_EXTENSION=c

# --- 

butilssh_TYPE=shlib

butilssh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
