TOPDIR=..

POSTBUILD_SUBDIRS=errorp

TARGETS:=butils butilssh


# - sexe target compiles all files in current directory with extension *.c

butils_TYPE=lib

butils_SRC_EXTENSION=c


butilssh_TYPE=shlib

butilssh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
