#!/bin/sh

set -x

gcc ex1.c -o ex1 -lm

gcc ex2.c -o ex2 -lm

gcc ex3.c -o ex3 -lm

OS_TYPE=`uname -o | sed -e 's#\/#-#g' -e 's#(#-#g' -e 's#)#-#g'` 
OS_VERSION=`uname -r | sed -e 's#/#-#g' -e 's#(#-#g' -e 's#)#-#g'`
ARCH=`uname -m`

ROOT=../../${OS_TYPE}-${OS_VERSION}-${ARCH}

gcc ex4.c -o ex4 -I../.. -L${ROOT}/lib -lcorothread -lnutils -lcutils -lm

