TOPDIR=../..

POSTBUILD_SUBDIRS=test

TARGETS:=rtlib rtlibsh


# - sexe target compiles all files in current directory with extension *.c

rtlib_TYPE=lib

rtlib_SRC_EXTENSION=c

# ----------------------------------------------------------------------

rtlibsh_TYPE=shlib

rtlibsh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
