TOPDIR=../..


TARGETS:=cpplibref cpplibrefs


cpplibref_TYPE=exe

cpplibref_SRC=ref.cpp

cpplibref_LIBS=cpplib stdc++



cpplibrefs_TYPE=shlib

cpplibrefs_SRC=ref.cpp

cpplibrefs_LIBS=cpplibso stdc++



TESTS=cpplibreftest


cpplibreftest_TYPE=exe

cpplibreftest_SRC_EXTENSION=cpp

cpplibreftest_LIBS=cpplib stdc++


include $(TOPDIR)/rules.make