TOPDIR=..

POSTBUILD_SUBDIRS=test

TARGETS:=webbylib


# - sexe target compiles all files in current directory with extension *.c

webbylib_TYPE=lib

webbylib_SRC_EXTENSION=c


include $(TOPDIR)/rules.make
