TOPDIR=..

POSTBUILD_SUBDIRS=test webbyimpl

TARGETS:=webbylib webbylibsh


# --------------------------------------------:w

webbylib_TYPE=lib

webbylib_SRC_EXTENSION=c

# --------------------------------------------:w

webbylibsh_TYPE=shlib

webbylibsh_SRC_EXTENSION=c



include $(TOPDIR)/rules.make
