TOPDIR=..

POSTBUILD_SUBDIRS=test 

TARGETS:=tutils tutilssh


# - sexe target compiles all files in current directory with extension *.c

tutils_TYPE=lib

tutils_SRC_EXTENSION=c


tutilssh_TYPE=shlib

tutilssh_SRC_EXTENSION=c

tutilssh_LIBS=cutils butils pthread




include $(TOPDIR)/rules.make
