TOPDIR=..



TARGETS:=vtest


# - sexe target compiles all files in current directory with extension *.c

vtest_TYPE=lib

vtest_SRC=vtest.c cuitestrunner.c



TESTS:=vtesttest

vtesttest_TYPE=exe

vtesttest_SRC=example.c

vtesttest_LIBS=vtest

include $(TOPDIR)/rules.make
