TOPDIR=../..


TESTS=errorp


# do not invoke the test program, test is run by the POSTBUILD script
TEST_TOOL=true


#----------------------------------------

errorp_TYPE=exe

errorp_SRC=errorp

errorp_LIBS=butils 

errorp_POSTBUILD=./run.sh

#----------------------------------------


include $(TOPDIR)/rules.make
